micronaut:
  application:
    name: registrationService

  metrics:
    binders:
      netty:
        queues:
          enabled: true

    export:
      datadog:
        enabled: false
        step: 20s

      otlp:
        enabled: false
        step: 20s

    tags:
      # Note that an `instance` tag is added at runtime in `Application.java`
      service: registration

  executors:
    scheduled:
      type: scheduled
      core-pool-size: 16
